# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wikipage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wikipage.proto',
  package='rcdn',
  serialized_pb=_b('\n\x0ewikipage.proto\x12\x04rcdn\"\xce\x01\n\x04Page\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05title\x18\x02 \x02(\t\x12\x0b\n\x03url\x18\x03 \x02(\t\x12\x0f\n\x07page_id\x18\x04 \x02(\x05\x12\x13\n\x0brevision_id\x18\x05 \x02(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x02(\t\x12\x0f\n\x07summary\x18\x07 \x02(\t\x12\x0c\n\x04html\x18\x08 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\t \x01(\t\x12\x1f\n\x05image\x18\n \x03(\x0b\x32\x10.rcdn.Page.Image\x1a\x15\n\x05Image\x12\x0c\n\x04link\x18\x01 \x02(\t\"%\n\tWikiPages\x12\x18\n\x04page\x18\x01 \x03(\x0b\x32\n.rcdn.Page')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PAGE_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='rcdn.Page.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='link', full_name='rcdn.Page.Image.link', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=231,
)

_PAGE = _descriptor.Descriptor(
  name='Page',
  full_name='rcdn.Page',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rcdn.Page.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='rcdn.Page.title', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='rcdn.Page.url', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_id', full_name='rcdn.Page.page_id', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='revision_id', full_name='rcdn.Page.revision_id', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='rcdn.Page.content', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summary', full_name='rcdn.Page.summary', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='html', full_name='rcdn.Page.html', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='category', full_name='rcdn.Page.category', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='rcdn.Page.image', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PAGE_IMAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=231,
)


_WIKIPAGES = _descriptor.Descriptor(
  name='WikiPages',
  full_name='rcdn.WikiPages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='rcdn.WikiPages.page', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=270,
)

_PAGE_IMAGE.containing_type = _PAGE
_PAGE.fields_by_name['image'].message_type = _PAGE_IMAGE
_WIKIPAGES.fields_by_name['page'].message_type = _PAGE
DESCRIPTOR.message_types_by_name['Page'] = _PAGE
DESCRIPTOR.message_types_by_name['WikiPages'] = _WIKIPAGES

Page = _reflection.GeneratedProtocolMessageType('Page', (_message.Message,), dict(

  Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
    DESCRIPTOR = _PAGE_IMAGE,
    __module__ = 'wikipage_pb2'
    # @@protoc_insertion_point(class_scope:rcdn.Page.Image)
    ))
  ,
  DESCRIPTOR = _PAGE,
  __module__ = 'wikipage_pb2'
  # @@protoc_insertion_point(class_scope:rcdn.Page)
  ))
_sym_db.RegisterMessage(Page)
_sym_db.RegisterMessage(Page.Image)

WikiPages = _reflection.GeneratedProtocolMessageType('WikiPages', (_message.Message,), dict(
  DESCRIPTOR = _WIKIPAGES,
  __module__ = 'wikipage_pb2'
  # @@protoc_insertion_point(class_scope:rcdn.WikiPages)
  ))
_sym_db.RegisterMessage(WikiPages)


# @@protoc_insertion_point(module_scope)
